custom action for pre-commit workflow has been created
eclipse-velocitas/vehicle-app-python-template pull request #11
Opened 2022-07-26 10:03 UTC by mml5bg

# Description

## Azure DevOps PBI/Task reference

AB#_[PBI/Task number]_

## Checklist

* [ ] Vehicle App can be started with dapr run and is connecting to vehicle data broker
* [ ] Vehicle App can process MQTT messages and call the seat service
* [ ] Vehicle App can be deployed to local K3D and is running
* [ ] Created/updated tests, if necessary. Code Coverage percentage on new code shall be >= 70%.
* [ ] Extended the documentation in Velocitas repo
* [ ] Extended the documentation in README.md

* [ ] Devcontainer can be opened successfully
* [ ] Devcontainer can be opened successfully behind a corporate proxy
* [ ] Devcontainer can be re-built successfully

* [ ] Release workflow is passing

2022-08-02 08:19 UTC, SebastianSchildt commented
The problem is the automated commit 
<img width="893" alt="image" src="https://user-images.githubusercontent.com/3707124/182326079-2f96a8ba-38a3-4b02-b4d1-72842304bee8.png">

Clean solutions
 - Do no use GH actions that change code/do commits. Bad style
 - If you want Linter/license checks just treat it as "check" and when it errors, go fix your code and make a new commit

Semi-clean solutions:
 - Fix your local branch, and force push

(Fast) solution:
 - Convince your committer(s)  to merge anyway
 (this is fast for you, but not the comitter, because he/she now needs to _manually_ check every commit, making sure all "non-automated"/non-trivial ones are signed off correctly)

2022-08-02 08:35 UTC, DocMoebiuz requested changes
Please add more information in the PR itself to help understand what the PR changed and what new concepts have been introduced.

From my understanding the PR takes care of:
* Making sure that the pre-commit hook when running locally and on GitHub in the cloud are using the same settings. (Can you please explain a bit more why this was not the case until now?)
* The execution of the pre-commit locally was not intuitive and is now performed automatically by VSCode on each save. 
  * Is this really convenient? I  have to try first 
  * Why is the pre-commit hook not executed by my git client BEFORE COMMITING changes in my local clone? It should fail locally and prevent me from committing changes. At the latest, when pushing.... but I have to read up on the pre-commit concept again.
  
  
The original request is still open. "Same settings for VSCode and CI Workflow".

2022-08-02 08:35 UTC, DocMoebiuz commented on .github/workflows/ci.yml
> -      - name: Clone Release Documentation Action repository
Why did the order change of this task?

2022-08-02 08:35 UTC, DocMoebiuz commented on .github/workflows/ci.yml
> -        uses: actions/checkout@v2
what exactly is the difference between v2 and v3?

2022-08-02 08:35 UTC, DocMoebiuz commented on .github/workflows/ci.yml
> -      - name: Clone Release Documentation Action repository
why did the order of this step change? it is now executed later.

2022-08-02 08:35 UTC, DocMoebiuz commented on .github/workflows/ci.yml
> -        uses: pre-commit/action@v3.0.0
Where did the old pre-commit action gets its settings from?

2022-08-02 09:23 UTC, mml5bg commented
> Please add more information in the PR itself to help understand what the PR changed and what new concepts have been introduced.
> 
> From my understanding the PR takes care of:
> 
>     * Making sure that the pre-commit hook when running locally and on GitHub in the cloud are using the same settings. (Can you please explain a bit more why this was not the case until now?)
> 
>     * The execution of the pre-commit locally was not intuitive and is now performed automatically by VSCode on each save.
>       
>       * Is this really convenient? I  have to try first
>       * Why is the pre-commit hook not executed by my git client BEFORE COMMITING changes in my local clone? It should fail locally and prevent me from committing changes. At the latest, when pushing.... but I have to read up on the pre-commit concept again.
> 
> 
> The original request is still open. "Same settings for VSCode and CI Workflow".
PR description is updated with approach and explanation.

Of course, you should try.
Now, it is executed before commiting and it is preventing to commit code before all issues are resolved. I already tested it.

And on the end. Original request is satisfied because, now configuration is exactly the same for VS Code and CI Workflow. How? Because, they are all using the same tool (pre-commit) and that tool uses the only one configuration file whenever it is executed (locally in VS Code or in CI Workflow). Now is not possible to have situation where someone commit something and CI workflow fails because of the linter issues, because of new setup, implemented in this PR.

2022-08-11 15:38 UTC, BjoernAtBosch reviewed
Looks fine for me

2022-09-27 15:33 UTC, BjoernAtBosch approved these changes

2022-09-28 09:29 UTC, DocMoebiuz approved these changes
Do we have impact on our documentation repository?
I think we should mention something about this feature if we haven't yet.

2022-09-28 09:54 UTC, merged