[10802] Improve local runtime scripts
eclipse-velocitas/vehicle-app-python-template pull request #17
Opened 2022-08-17 13:33 UTC by dennismeister93

Signed-off-by: Dennis Meister <dennis.meister@bosch.com>

# Description

Idea is to use the already existing docker images (also used in k3s) for local runtime instead of downloading binaries.
The runtime runs with docker containers and dapr as a sidecar processes.

Additionally the prerequisites_settings.json got replaced with the AppManifest.json.
All relevant scripts are adapted accordingly.

run-seatservice.sh is renamed to run-vehicleservices.sh which gets all configured services from the AppManifest.json and runs them.

## Azure DevOps PBI/Task reference

[AB#_[10802]_](https://softwaredefinedvehicle.visualstudio.com/SoftwareDefinedVehicle/_workitems/edit/10802)

## Checklist

* [x] Vehicle App can be started with dapr run and is connecting to vehicle data broker
* [x] Vehicle App can process MQTT messages and call the seat service
* [x] Vehicle App can be deployed to local K3D and is running
* [ ] Extended the documentation in Velocitas repo
* [ ] Extended the documentation in README.md

* [x] Devcontainer can be opened successfully
* [ ] Devcontainer can be opened successfully behind a corporate proxy
* [x] Devcontainer can be re-built successfully

* [ ] Release workflow is passing

2022-08-23 09:37 UTC, rom3be approved these changes

2022-08-29 09:18 UTC, emsameen commented on .vscode/scripts/runtime/k3d/deploy_runtime.sh
> +    UTILS_DIRECTORY=$(dirname `cd ..; dirname "$0"`)/utils
As discussed, the Integration test is failing due to the relative path of the UTILS_DIRECTORY  directory, Please use the ROOT_DIRECTORY for all scripts for consistency. 

Thanks!

2022-08-29 09:19 UTC, emsameen requested changes
UTILS_DIRECTORY

2022-08-29 09:54 UTC, emsameen approved these changes
LGTM

2022-08-29 09:54 UTC, merged