use ruff as linter
eclipse-velocitas/vehicle-app-python-template pull request #220
Opened 2024-01-17 12:19 UTC by MP91

# Description

## Issue ticket number and link

## Checklist

* [ ] Vehicle App can be started with dapr run and is connecting to vehicle data broker
* [ ] Vehicle App can process MQTT messages and call the seat service
* [ ] Vehicle App can be deployed to local K3D and is running
* [ ] Created/updated tests, if necessary. Code Coverage percentage on new code shall be >= 70%.
* [ ] Extended the documentation in Velocitas repo
* [ ] Extended the documentation in README.md

* [ ] Devcontainer can be opened successfully
* [ ] Devcontainer can be opened successfully behind a corporate proxy
* [ ] Devcontainer can be re-built successfully

* [ ] Release workflow is passing

2024-01-17 12:23 UTC, MP91 commented on .velocitas.json
> -            "version": "v1.4.5"
use correct tag

2024-01-18 06:37 UTC, doosuu requested changes

2024-01-18 06:37 UTC, doosuu commented on NOTICE.md
> +|   GRPC     |           https://github.com/grpc/grpc/blob/master/LICENSE           |
Fix alignment and spelling on gRPC.

2024-01-18 06:37 UTC, doosuu commented on setup.cfg
Let's create a follow-up issue to switch to pyproject.toml?

2024-01-18 11:36 UTC, doosuu commented on setup.cfg
Not specific to ruff - pyproject.toml is the new de-facto standard. While setup.py is not deprecated, I would recommend we switch at some point.

2024-01-22 07:47 UTC, MP91 commented on .velocitas.json
> -            "version": "v1.4.5"
done

2024-01-22 07:48 UTC, MP91 commented on NOTICE.md
> +|   GRPC     |           https://github.com/grpc/grpc/blob/master/LICENSE           |
done

2024-01-22 10:42 UTC, doosuu approved these changes
lgtm

2024-01-22 10:42 UTC, merged