Updating SDK dependency
eclipse-velocitas/vehicle-app-python-template pull request #256
Opened 2024-08-08 09:01 UTC by erikbosch

Upgrading dependencies to fix vulnerabilities.
I see no real need to have explicit dependencies for many of the packages, as we do not intend to use them directly from the app, but rather indirectly through the SDK, or?

2024-08-08 11:08 UTC, dennismeister93 requested changes

2024-08-08 11:08 UTC, dennismeister93 commented on app/requirements.in
> +velocitas-sdk==0.15.1
lets wait for 0.15.2

2024-08-08 13:23 UTC, erikbosch commented on app/requirements.in
> +velocitas-sdk==0.15.1
Agree,

2024-08-08 14:39 UTC, erikbosch commented on app/requirements.in
> +velocitas-sdk==0.15.1
Updated

2024-08-12 04:47 UTC, doosuu approved these changes
lgtm

2024-09-03 08:07 UTC, erikbosch commented
I would say this one is replaced by #257, closing it

2024-09-03 08:07 UTC, closed without merging